import esbuild from "esbuild";
import process from "process";
import path from "node:path";
import { builtinModules } from 'node:module';
import { copyFileSync } from 'node:fs';

import esbuildSvelte from 'esbuild-svelte';
import { sveltePreprocess } from 'svelte-preprocess';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const srcLib = path.resolve("src/lib");

try {
	copyFileSync("node_modules/sql.js/dist/sql-wasm.wasm", "sql-wasm.wasm");
} catch (e) {
	console.warn("Could not copy sql-wasm.wasm (deps might not be installed yet):", e.message);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [
		// resolve $/ and $lib/ to src/lib/
		{
			name: "dollar-alias",
			setup(build) {
				build.onResolve({ filter: /^\$\// }, args => ({
					path: path.resolve(srcLib, args.path.slice(2)),
				}));
				build.onResolve({ filter: /^\$lib\// }, args => ({
					path: path.resolve(srcLib, args.path.slice(5)),
				}));
			},
		},
		esbuildSvelte({
			compilerOptions: {
				css: 'injected',
			},
			preprocess: [sveltePreprocess({
				scss: {
					importer(url) {
						if (!url.startsWith('$/')) return null;
						return { file: path.resolve(srcLib, url.slice(2)).replace(/\\/g, '/') };
					},
				},
			})],
		}),
	],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "esnext",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
