CREATE TABLE IF NOT EXISTS Tables(
    id INTEGER PRIMARY KEY,
    label TEXT,
    created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Columns(
    id INTEGER PRIMARY KEY,
    table_id INTEGER REFERENCES Tables(id) ON DELETE CASCADE,
    label TEXT,
    datatype TEXT,
    created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Rows(
    id INTEGER PRIMARY KEY,
    table_id INTEGER REFERENCES Tables(id) ON DELETE CASCADE,
    created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Cells(
    row_id INTEGER REFERENCES Rows(id) ON DELETE CASCADE,
    column_id INTEGER REFERENCES Columns(id) ON DELETE CASCADE,
    value TEXT,

    PRIMARY KEY (row_id, column_id)
);


CREATE TABLE IF NOT EXISTS Enums(
    id INTEGER PRIMARY KEY,
    label TEXT,
    created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS EnumVariants(
    id INTEGER PRIMARY KEY,
    enum_id INTEGER REFERENCES Enums(id) ON DELETE CASCADE,
    label TEXT,
    created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- CREATE TABLE IF NOT EXISTS EnumVariantColumns(
--     id INTEGER PRIMARY KEY,
--     variant_id INTEGER REFERENCES EnumVariants(id) ON DELETE CASCADE,
--     label TEXT,
--     datatype TEXT,
--     created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
--     updated_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
-- );