CREATE TABLE IF NOT EXISTS Tables(
    id INTEGER PRIMARY KEY,
    label TEXT,
    created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Columns(
    id INTEGER PRIMARY KEY,
    table_id INTEGER REFERENCES Tables(id) ON DELETE CASCADE,
    label TEXT,
    datatype TEXT,
    created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Rows(
    id INTEGER PRIMARY KEY,
    table_id INTEGER REFERENCES Tables(id) ON DELETE CASCADE,
    created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Cells(
    row_id INTEGER REFERENCES Rows(id) ON DELETE CASCADE,
    column_id INTEGER REFERENCES Columns(id) ON DELETE CASCADE,
    value TEXT,

    PRIMARY KEY (row_id, column_id)
);